Feature/milestone 1
root-code-software/Tic-Tac-Toe pull request #2
Opened 2019-10-29 23:18 UTC by Israel-Laguan

# Resume

We have created the methods as described in the project requirements, added some basic tests, and *came to the conclusion that we met all of the requirements*.

# Proposal

we want to have a review of the code to know if we need to make any changes. If no changes needed we want the project to be ACCEPTED so we can move to the next project with a happy smile :)

# Comments

Working on ruby is interesting because of new concepts, but is a good thing that ruby have a lot of good utilities that helps a lot. It is an interesting language to work with.

Besides that working in organizing files and folders was fun.

2019-10-31 07:15 UTC, bolah2009 approved these changes
### Hi Team :wave: 

Nice job making the `main.rb` file executable. :clap: 

Please prevent the use of `puts`, `p`, `gets`, `prints` or any other user interaction from the `lib` directory in future milestones. 

#### It's a :+1: from me. 

Let's move to Milestone 2

#### :heavy_check_mark: Approved.

2019-10-31 07:15 UTC, bolah2009 commented on lib/tic_tac_toe.rb
> +p 'Hello world!'
Let's delete this

> `main.rb` file should be responsible for user interaction. This is the only one place where `puts` and `get.chomp` can be used.

2019-11-01 14:51 UTC, Israel-Laguan commented on lib/tic_tac_toe.rb
> +p 'Hello world!'
Sure man, thanks for the review!

2019-11-02 08:57 UTC, maelfosso requested changes
Hello @Israel-Laguan @izaiasneto4 ,

Please, you didn't make the changes suggested by @bolah2009 

Kindly do and submit a new code review request.
Thanks.

**Mael FOSSO**
[Github](https://github.com) | [Twitter](https://twitter.com) | [LinkedIn](https://www.linkedin.com/in/mael-elvis-fosso-650b6346/)

2019-11-02 08:57 UTC, maelfosso commented on lib/tic_tac_toe.rb
> +p 'Hello world!'
Please, it's still there

2019-11-04 04:44 UTC, whiz25 approved these changes
## Good job implementing the changes
It's a :+1: from me.

### Martin Afani

2019-11-04 15:57 UTC, merged